language: cpp

before_install:
 - if [[ $SET = cnc ]]; then sudo add-apt-repository -y ppa:yani/iatsl; fi
 - sudo apt-get update
 - sudo apt-get install libblas-dev liblapack-dev libhiredis-dev libboost-dev redis-server
 - if [[ $SET = circle ]]; then sudo apt-get install libboost-serialization-dev libopenmpi-dev openmpi-bin; fi
 - if [[ $SET = cnc ]]; then sudo apt-get install libtbb-dev cmake; fi

before_script:
  - if [[ $SET = circle ]]; then 
      git clone --depth=1 https://github.com/hpc/libcircle.git && 
      cd libcircle && 
      ./configure && make && sudo make install &&
      export LD_LIBRARY_PATH=/usr/local/lib &&
      cd ..;
    fi
  - if [[ $SET = charm ]]; then 
      git clone --depth=1 http://charm.cs.uiuc.edu/gerrit/charm && 
      cd charm && 
      ./build charm++ net-linux-x86_64 -j4 && export CHARM_ROOT=$PWD &&
      cd ..;
    fi
  - if [[ $SET = cnc ]]; then 
      git clone --depth=1 https://github.com/icnc/icnc.git && 
      cd icnc &&
      cmake . &&
      make -j4 && sudo make install && export CNCROOT=/usr/local &&
      export LD_LIBRARY_PATH=/usr/local/lib/intel64 &&
      cd ..;
    fi

env:
  - SET=omp
  - SET=circle
  - SET=charm
  - SET=cnc
  - SET=serial

script:
  - if [[ $SET = cnc ]]; then 
      make -j4 SET="${SET}" OPTFLAGS="-O3 -Werror -DCNC_REQUIRED_TBB_VERSION=6101" HIREDIS_INCLUDES=/usr/include BOOST_INCLUDES=/usr/include CXX="${CXX}";
    elif [[ $SET = circle ]]; then
      make -j4 SET="${SET}" OPTFLAGS="-O3 -Werror -U_FORTIFY_SOURCE" HIREDIS_INCLUDES=/usr/include BOOST_INCLUDES=/usr/include;
    else
      make -j4 SET="${SET}" OPTFLAGS="-O3 -Werror" HIREDIS_INCLUDES=/usr/include BOOST_INCLUDES=/usr/include;
    fi
  - nohup redis-server &
  - sed -i '/integration steps/s/25/1/' input.json
  - ${SET}_bin/2D_Kriging input.json;

compiler:
  - gcc
